"""LateLog datetime issues again

Revision ID: 3b5101bc3047
Revises: dcc15719e54e
Create Date: 2024-12-10 17:26:00.450048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5101bc3047'
down_revision = 'dcc15719e54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
